parser grammar MarkdownGrammar;

options {tokenVocab=MarkdownLexer;}

cv:info BLOCKSPLITTER (block BLOCKSPLITTER)*;

info: SHARP (STRING_LITERAL)+ NEWLINE subHeader;
subHeader:(SHARP SHARP (STRING_LITERAL)+ NEWLINE)+ address;
address: STAR STRING_LITERAL NEWLINE contacts+;
contacts: CLOSE_ANGLE_BRACKET icon STRING_LITERAL NEWLINE;

block: SHARP SHARP STRING_LITERAL;

icon: OPEN_CURLY STRING_LITERAL (REAL SLASH NUMBER)? CLOSE_CURLY;